//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_S39_Commander.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        //setting_LineExtEnabled
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string setting_LineExtEnabled {
            get {
                return ((string)(this["setting_LineExtEnabled"]));
            }
            set {
                this["setting_LineExtEnabled"] = value;
            }
        }       
        
        //setting_ConnectionCheck
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string setting_ConnectionCheck {
            get {
                return ((string)(this["setting_ConnectionCheck"]));
            }
            set {
                this["setting_ConnectionCheck"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string setting_LogCatAutoStart {
            get {
                return ((string)(this["setting_LogCatAutoStart"]));
            }
            set {
                this["setting_LogCatAutoStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string setting_AutoOpenCSV {
            get {
                return ((string)(this["setting_AutoOpenCSV"]));
            }
            set {
                this["setting_AutoOpenCSV"] = value;
            }
        }        
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public string setting_DelayTime {
            get {
                return ((string)(this["setting_DelayTime"]));
            }
            set {
                this["setting_DelayTime"] = value;
            }
        }             
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public string setting_PauseDuration {
            get {
                return ((string)(this["setting_PauseDuration"]));
            }
            set {
                this["setting_PauseDuration"] = value;
            }
        }                
        
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setting_ADBpath {
            get {
                return ((string)(this["setting_ADBpath"]));
            }
            set {
                this["setting_ADBpath"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setting_ADBstart {
            get {
                return ((string)(this["setting_ADBstart"]));
            }
            set {
                this["setting_ADBstart"] = value;
            }
        }            
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setting_ADBcommand {
            get {
                return ((string)(this["setting_ADBcommand"]));
            }
            set {
                this["setting_ADBcommand"] = value;
            }
        }    
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setting_ADBFilter {
            get {
                return ((string)(this["setting_ADBFilter"]));
            }
            set {
                this["setting_ADBFilter"] = value;
            }
        }    
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setting_ADBstop {
            get {
                return ((string)(this["setting_ADBstop"]));
            }
            set {
                this["setting_ADBstop"] = value;
            }
        }       
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setting_ADBFOTAFilter {
            get {
                return ((string)(this["setting_ADBFOTAFilter"]));
            }
            set {
                this["setting_ADBFOTAFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setting_FOTAVendorSpecific {
            get {
                return ((string)(this["setting_FOTAVendorSpecific"]));
            }
            set {
                this["setting_FOTAVendorSpecific"] = value;
            }
        }       
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setting_FOTADefaultPath {
            get {
                return ((string)(this["setting_FOTADefaultPath"]));
            }
            set {
                this["setting_FOTADefaultPath"] = value;
            }
        }        
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setting_ExcelTemplate {
            get {
                return ((string)(this["setting_ExcelTemplate"]));
            }
            set {
                this["setting_ExcelTemplate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setting_StatsPath {
            get {
                return ((string)(this["setting_StatsPath"]));
            }
            set {
                this["setting_StatsPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setting_InjectionPath {
            get {
                return ((string)(this["setting_InjectionPath"]));
            }
            set {
                this["setting_InjectionPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setting_PythonPath {
            get {
                return ((string)(this["setting_PythonPath"]));
            }
            set {
                this["setting_PythonPath"] = value;
            }
        }
        
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public System.Collections.Specialized.StringCollection Setting_WatchList {
            get {
        		return (System.Collections.Specialized.StringCollection)(this["Setting_WatchList"]);
            }
            set {
                this["Setting_WatchList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setting_HeartBeatMessage {
            get 
            {
                return ((string)(this["setting_HeartBeatMessage"]));
            }
            set 
            {
                this["setting_HeartBeatMessage"] = value;
            }
        }
        
	     [global::System.Configuration.UserScopedSettingAttribute()]
         [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]  
         [global::System.Configuration.DefaultSettingValueAttribute("0.00:00:00")] 
         public global::System.TimeSpan setting_BluetoothTimeout {             
         	get 
         	{
         		return ((global::System.TimeSpan)(this["setting_BluetoothTimeout"]));               
         	}
            set 
            {
                this["setting_BluetoothTimeout"] = value;
            }         	
         }
        
    }
}
